/**
* The audio package provides an audio player supporting the following extensions:
* <ul>
* <li>mp3</li>
* <li>wav</li>
* <li>aif</li>
* <li>au</li>
* </ul>
* The <code>SoundPlayer</code> in the media package is multipurpose and also supports playing MIDI files,
* but if you only need an audio player to play single files you can choose this option.
 * It also provides an audio recorder supporting the following extensions:
 * <ul>
 * <li>wav</li>
 * <li>aif</li>
 * <li>au</li>
 * </ul>
 * An instance object of AudioRecorder allows you to record and save audio files
 * for the allowed extensions.
 *
 * There are more useful components:
 * <code>Oscillator</code>
 * With an instance object of this class you can generate sinusoidal waves oscillating at any frequency.
 *
 * <code>Envelope</code>
 * Using this class you can generate ADSR envelopes, for example, to apply to a wave generated by an <code>Oscillator</code> object.
 *
 * <code>RawDataPlayer</code>
 * This class allows you to play raw data.
 * For example, data generated by an oscillator.
 *
 * <code>RawDataStorage</code>
 * Using this class, you are able to store raw data in an audio file.
 *
 * Some classes in this package use assertions. so, you have to run them with the 'ea' modifier
 * which enables assertions.
 * Example:
 * <code>java -ea MyApp</code>
 *
*/

package imr.media.audio;
